version: "3.1"
services:
#  mongo:
#    image: mongo:4.0
#    container_name: "malware_domains_db"
#    hostname: mongo
#    ports:
#      - 27017:27017
#    command: --smallfiles
#    volumes:
#      - ./data/db:/data/malware
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
  api:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo